# Basic
title: Brody
subtitle: 月亮和六便士都会在你眼前
welcome_message: #<a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: Vno Jekyll is a port of my Ghost theme vno.
creator: <a href="#">@Brody</a>

url: ""

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: 阅读
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: '#'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: gaolianbo
    github: googlb
    twitter: gaolianbo
    gplus: 
    mail: gaolianbo@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
